// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPi7AnDaFS4KFTbXuh0DHCH8ltLbK0jo',
    appId: '1:942644392160:web:389b47d3b2e428ff57e085',
    messagingSenderId: '942644392160',
    projectId: 'innova-smg',
    authDomain: 'innova-smg.firebaseapp.com',
    storageBucket: 'innova-smg.appspot.com',
    measurementId: 'G-TJX4QSW4R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdramTSe1wWnYPXmTo1Luityik_jGI1Q',
    appId: '1:942644392160:android:f3508e5c9b71a12557e085',
    messagingSenderId: '942644392160',
    projectId: 'innova-smg',
    storageBucket: 'innova-smg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXTk0HYbmms_LmWCdf8XDYnCvtSVvU9js',
    appId: '1:942644392160:ios:de834ca7c90db49757e085',
    messagingSenderId: '942644392160',
    projectId: 'innova-smg',
    storageBucket: 'innova-smg.appspot.com',
    androidClientId: '942644392160-e257tljkti4igd8u53j8qvgfc4157dmf.apps.googleusercontent.com',
    iosClientId: '942644392160-0l8q0rr9b9pbbl1kinqv59va2tm2uicr.apps.googleusercontent.com',
    iosBundleId: 'com.studymatchglobal.wizard.smg',
  );
}
